apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-signed-container-images
  annotations:
    policies.kyverno.io/title: Verify signed container images
    policies.kyverno.io/category: Supply Chain Security
spec:
  validationFailureAction: Audit
  background: false
  rules:
    - name: require-signed-images
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "ghcr.io/kyverno/test-verify-image*"
          mutateDigest: false
          verifyDigest: false
          attestors:
            - count: 1
              entries:
                - keys:
                    publicKeys: |-
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEstG5Xl7UxkQsmLUxdmS85HLgYBFy
                      c/P/oQ22iazkKm8P0sNlaZiaZC4TSEea3oh2Pim0+wxSubhKoK+7jq9Egg==
                      -----END PUBLIC KEY-----
