"""Mint X.509 certificates for tests.

Committed PEM fixtures rot. Every fixture in ``tests/certificates`` carried a
fixed notBefore of 2026-03-16, so by September 2026 five of the six had
expired -- including ``valid_cert.pem``, which the CI matrix asserted exits 0.
Nothing noticed, because until report schema 2.0 nothing compared notAfter to
the evaluation time.

Tests that need a *currently valid* certificate therefore mint one here rather
than reading a file. Committed fixtures remain for the CI matrix and for
artefacts that cannot be generated (see ``SHA1_IS_UNMINTABLE``), and
``test_certificate_fixtures.py`` fails if one of them drifts toward expiry.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Iterable, Literal

from cryptography import x509
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import ec, ed25519, rsa
from cryptography.hazmat.primitives.serialization import Encoding
from cryptography.x509.oid import NameOID

#: cryptography >= 42 refuses to produce SHA-1 signatures, so a SHA-1 test
#: artefact cannot be minted at runtime and must stay a committed fixture.
SHA1_IS_UNMINTABLE = True

#: Fixtures that are expired on purpose and must not trigger the freshness
#: guard. Anything else in tests/certificates is expected to stay valid.
INTENTIONALLY_EXPIRED_FIXTURES: frozenset[str] = frozenset(
    {"sha1_cert.pem", "expired_cert.pem"}
)

KeyKind = Literal[
    "rsa2048", "rsa3072", "rsa1024", "ec256", "ec384", "ec192", "ed25519"
]


@dataclass(frozen=True)
class CertSpec:
    """Everything a test needs to vary about a certificate."""

    common_name: str = "example.com"
    san_dns: tuple[str, ...] = ("example.com", "www.example.com")
    validity_days: int = 90
    validity_hours: int = 0
    key: KeyKind = "rsa2048"
    hash_algorithm: str = "sha256"
    #: Shift the whole validity window. Negative puts it in the past (expired),
    #: positive puts it in the future (not yet valid).
    starts_in_days: int = 0
    basic_constraints_ca: bool | None = None
    include_ski: bool = False
    include_eku: tuple[str, ...] | None = None
    serial_number: int | None = None


def _private_key(kind: KeyKind):
    if kind == "rsa2048":
        return rsa.generate_private_key(public_exponent=65537, key_size=2048)
    if kind == "rsa3072":
        return rsa.generate_private_key(public_exponent=65537, key_size=3072)
    if kind == "rsa1024":
        # Deliberately weak, for the key-size control.
        return rsa.generate_private_key(public_exponent=65537, key_size=1024)
    if kind == "ec256":
        return ec.generate_private_key(ec.SECP256R1())
    if kind == "ec384":
        return ec.generate_private_key(ec.SECP384R1())
    if kind == "ec192":
        # Below the BR 6.1.5 floor and not an approved curve. This is the case
        # that previously evaluated as fully compliant.
        return ec.generate_private_key(ec.SECP192R1())
    if kind == "ed25519":
        return ed25519.Ed25519PrivateKey.generate()
    raise ValueError(f"Unsupported key kind: {kind}")


def _hash(name: str) -> hashes.HashAlgorithm | None:
    mapping = {
        "sha256": hashes.SHA256(),
        "sha384": hashes.SHA384(),
        "sha512": hashes.SHA512(),
    }
    if name == "sha1":
        raise ValueError(
            "SHA-1 signatures cannot be generated by this cryptography version; "
            "use the committed tests/certificates/sha1_cert.pem fixture."
        )
    try:
        return mapping[name]
    except KeyError as exc:
        raise ValueError(f"Unsupported hash algorithm: {name}") from exc


def write_certificate(path: Path, spec: CertSpec = CertSpec()) -> Path:
    """Write a PEM certificate matching ``spec`` and return its path."""
    key = _private_key(spec.key)
    now = datetime.now(timezone.utc)
    not_before = now + timedelta(days=spec.starts_in_days) - timedelta(minutes=5)
    not_after = not_before + timedelta(
        days=spec.validity_days, hours=spec.validity_hours
    )

    name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, spec.common_name)])
    builder = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(name)
        .public_key(key.public_key())
        .serial_number(
            spec.serial_number
            if spec.serial_number is not None
            else x509.random_serial_number()
        )
        .not_valid_before(not_before)
        .not_valid_after(not_after)
    )
    if spec.san_dns:
        builder = builder.add_extension(
            x509.SubjectAlternativeName([x509.DNSName(d) for d in spec.san_dns]),
            critical=False,
        )
    if spec.basic_constraints_ca is not None:
        builder = builder.add_extension(
            x509.BasicConstraints(ca=spec.basic_constraints_ca, path_length=None),
            critical=True,
        )
    if spec.include_ski:
        builder = builder.add_extension(
            x509.SubjectKeyIdentifier.from_public_key(key.public_key()),
            critical=False,
        )
    if spec.include_eku is not None:
        builder = builder.add_extension(
            x509.ExtendedKeyUsage(
                [x509.ObjectIdentifier(oid) for oid in spec.include_eku]
            ),
            critical=False,
        )

    if isinstance(key, ed25519.Ed25519PrivateKey):
        certificate = builder.sign(private_key=key, algorithm=None)
    else:
        certificate = builder.sign(
            private_key=key, algorithm=_hash(spec.hash_algorithm)
        )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(certificate.public_bytes(Encoding.PEM))
    return path


def fixture_expiry_report(
    fixture_dir: Path, names: Iterable[str] | None = None
) -> list[dict[str, object]]:
    """Describe each committed fixture's validity window.

    Used by the freshness guard so a fixture cannot silently expire again.
    """
    report: list[dict[str, object]] = []
    now = datetime.now(timezone.utc)
    candidates = (
        [fixture_dir / n for n in names]
        if names is not None
        else sorted(fixture_dir.glob("*.pem"))
    )
    for path in candidates:
        certificate = x509.load_pem_x509_certificate(path.read_bytes())
        report.append(
            {
                "name": path.name,
                "not_before": certificate.not_valid_before_utc,
                "not_after": certificate.not_valid_after_utc,
                "days_until_expiry": (certificate.not_valid_after_utc - now).days,
                "expired": certificate.not_valid_after_utc < now,
                "intentionally_expired": path.name
                in INTENTIONALLY_EXPIRED_FIXTURES,
            }
        )
    return report
